// <auto-generated />
namespace Ejemplo_Clase3.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Agregar_Edad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregar_Edad));
        
        string IMigrationMetadata.Id
        {
            get { return "201904132203243_Agregar_Edad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
