// <auto-generated />
namespace Ejemplo_Clase3.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Agregar_Direccion_Modelo_Personas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregar_Direccion_Modelo_Personas));
        
        string IMigrationMetadata.Id
        {
            get { return "201904132117074_Agregar_Direccion_Modelo_Personas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
